networks:
  app_net:
    driver: bridge
  postgres_network:
      external: true
services:
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: amocrm_users
    ports:
      - "7000:8000"
    networks:
      - app_net
      - postgres_network
