version: "3.8"
networks:
  app_net:
    driver: bridge
  postgres_network:
      external: true
services:
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: amocrm_users
    ports:
      - 7000:8000
    depends_on:
      - postgres_db
    networks:
      - app_net
      - postgres_network
