networks:
  rabbitmq_rabbit-net:
    external: true
  postgres_network:
      external: true
services:
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: amocrm_users
    ports:
      - "7000:8000"
    networks:
      - postgres_network
      - rabbitmq_rabbit-net
