version: "3.8"
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
services:
  db:
    image: postgres:latest
    container_name: users_amo_db
    ports:
      - 5432:5432
    env_file:
      - .env-non-dev
    networks:
      - app_net

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: amocrm_users
    ports:
      - 7000:8000
    depends_on:
      - db
    networks:
      - app_net
