"""add new column client_secret

Revision ID: b2ee3b6b1d18
Revises: 4e02f9b1c528
Create Date: 2024-07-18 19:16:40.149302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ee3b6b1d18'
down_revision: Union[str, None] = '4e02f9b1c528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_secret', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'client_secret')
    # ### end Alembic commands ###
