"""refactor models

Revision ID: c2ca3bde9023
Revises: 986de98b08e9
Create Date: 2024-07-19 15:10:31.634351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ca3bde9023'
down_revision: Union[str, None] = '986de98b08e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'client_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_secret', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
